config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  devise_for :users

  resources :events do
    resources :attendances, only: [:index]
  end
  resources :users, only: [:show, :update, :edit]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
  
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, presence: true
    validates :duration, presence: true, numericality: { only_integer: true, multiple_of: 5, greater_than: 0, }
    validates :title, presence: true, length: {in: 5..140}
    validates :description, presence: true, length: {in: 20..1000}
    validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 } 
    validates :location, presence: true 
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :user
    validate :start_must_be_before_end_date
    

    # def end_date()
    #     duration_sec = :duration * 60
    #     duration_datetime = Time.at(duration_sec).to_datetime
    #     return :start_date + duration_datetime
    # end

    def start_must_be_before_end_date()
        datetime_now = DateTime.now
        start_date = self.start_date
        errors.add(:start_date, "Tu veux vraiment finir tes vacances avant de les avoir terminées ?") if 
            start_date < datetime_now
    end 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def index()
        @events = Event.all
    end

    def create()
        @event = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], user: current_user)
        if @event.save
            redirect_to events_path
            flash[:success] = "Votre événement a bien été créé"
        else
            redirect_to new_event_path
            flash[:error] = "Un ou plusieurs erreurs ont été détectée : #{@event.errors.full_messages.join(",")}"
        end
    end

    def show()
        id = params[:id]
        @event = Event.find(id)
    end

    def edit()
        id = params[:id]
        @event = Event.find(id)
    end

    def update()
        id = params[:id]
        @event = Event.find(id)
        @update = @event.update(title: params[:title], description: params[:description], price: params[:price], location: params[:location])
        if @update
            redirect_to "/events/#{@event.id}"
            flash[:success] = "Ton événement a bien été modifié"
        else
            redirect_to "/events/#{@event.id}/edit"
            flash[:error] = "Une erreur a été détecté :#{@event.errors.full_messages.join(",")}"
        end 
    end

    def destroy()
        id = params[:id]
        @event = Event.find(id)
        @event.destroy
        redirect_to root_path
        flash[:success] = "Votre événement a bien été supprimé"
    end

end

app/helpers/events_helper.rb
module EventsHelper

    def current_user?(event)
        if event.user == current_user
            return true
        else
            return false
        end
    end

end

app/views/events/_header.html.erb
 <header class="header_2">
        <nav class="navbar navbar-expand-lg">
            <div class="inline space_between">
                <div class=inline>
                    <a class="logo" href="/">Eventbrite</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <div class=inline>
                            <a class="a_nav" href="/events/new">Créer un événement</a>
                        </div>
                    </div>
                </div>
                
                    <%if user_signed_in?%>
                    <div class="dropdown">
                        <button class="btn btn_nav dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mon compte
                        </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item btn" href="/users/<%= current_user.id%>">Profil</a>
                                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class:"dropdown-item btn" %>

                            </div>
                    <%else%>
                    <div class=inline>
                        <%= link_to "S'inscrire", new_user_registration_path, class:"btn_nav btn"%>
                        <%= link_to "Se connecter", new_user_session_path, class:"btn_nav btn" %>
                    </div>
                    <%end%>
                </div>
            </div>
        </nav>
    </header>

app/views/events/edit.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Modifier l'événement</title>
</head>
<body>
    <%if flash[:error]%>
        <div class="alert alert-danger" role="alert">
            <%= flash[:error]%>
        </div>
        <%elsif flash[:success]%>
        <div class="alert alert-success" role="alert">
            <%= flash[:success]%>
        </div>
    <%end%>
  <main>
    <section class="section_center">
     <h1> Modifie ton événement </h1>
        <%= form_tag url_for(controller: "events", action: "update"), method: "patch" do%>
            <div class= "form_inscription forms_gap">
              <div>
                <%= label_tag :title, "Titre"%>
                <%= text_field_tag :title, @event.title, class:"form-control"%>
              </div>
              <div>
                <%= label_tag :description, "Description"%>
                <%= text_area_tag :description, @event.description, class:"form-control description"%>
              </div>
              <div class=inline>
                <div>
                  <%= label_tag :price, "Prix"%>
                  <%= number_field_tag :price, @event.price, class:"form-control"%>
                </div>
              </div>
              <div class=inline>
                <div>
                  <%= label_tag :location, "Lieu"%>
                <%= text_field_tag :location, @event.location, class:"form-control"%>
                </div>
              </div>
                  <%= submit_tag "Valider", class:'btn btn_inscription btn_primary'%>
            </div>
        <%end%>
        <%= button_to "Supprimer l'événement", @event, method: :delete, class:'btn btn_inscription btn_primary'%>
    </section>
  </main>
</body>
</html>
      
    </section>
  </main>
</body>
</html>

app/views/events/index.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Tous les événements</title>
</head>
<body>
  <main>
    <%= render 'header' %>
    <%= render 'layouts/flash' %>
    <%= render 'hero_banner' %>
    <%= render 'image_text' %>
    <section>
      <h1> Tous les événements </h1>
          <div class=cards>
            <%@events.each do |event|%>
            <div class="card color_card" style="width: 18rem;">
                <div class="card-body">
                  <h2 class=color_font><%= event.title%></h2>
                  <div class="inline margin_bottom">
                    <div class=infos_accueil>
                      <i class="bi bi-geo-alt-fill small_icone"></i> <%= event.location%>
                    </div>
                    <div class=infos_accueil>
                      <i class="bi bi-calendar-event small_icone"></i> <%= event.start_date.strftime('%d'"/"'%m')%>
                    </div>
                  </div>
                  <p><%= event.description%></p>
                    <div class="inline space_between price_plus">
                      <div class=price>
                        <%= event.price%>€
                      </div>
                      <div class="plus_icone_div">
                      <a href="/events/<%= event.id%>" class="btn btn-primary plus_icone"><i class="bi bi-plus"></i></a>
                      </div>
                    </div>
                </div>
            </div>
            <%end%>
          </div>
    </section>
    </section>
  </main>
</body>
</html>

app/views/events/new.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Créer un événement</title>
</head>
<body>
  <main>
    <section class="section_center">
      <%if flash[:error]%>
        <div class="alert alert-danger" role="alert">
            <%= flash[:error]%>
        </div>
        <%elsif flash[:success]%>
        <div class="alert alert-success" role="alert">
            <%= flash[:success]%>
        </div>
      <%end%>
     <h1> Créer un événement </h1>
        <%= form_tag url_for(controller: "events", action: "create"), method: "post" do%>
            <div class= "form_inscription forms_gap">
              <div>
                <%= label_tag :title, "Titre"%>
                <%= text_field_tag :title, nil, class:"form-control"%>
              </div>
              <div>
                <%= label_tag :description, "Description"%>
                <%= text_area_tag :description, nil, class:"form-control description"%>
              </div>
              <div class=inline>
                <div>
                  <%= label_tag :location, "Lieu"%>
                  <%= text_field_tag :location, nil, class:"form-control"%>
                </div>
                <div>
                  <%= label_tag :price, "Prix"%>
                  <%= number_field_tag :price, nil, class:"form-control"%>
                </div>
              </div>
              <div class=inline>
                <div>
                  <%= label_tag :start_date, "Date de début"%>
                  <%= datetime_field_tag :start_date, nil, class:"form-control"%>
                </div>
                <div>
                  <%= label_tag :duration, "Durée en minute"%>
                  <%= number_field_tag :duration, nil, class:"form-control"%>
                </div>
              </div>
                  <%= submit_tag "Valider", class:'btn btn_inscription btn_primary'%>
            </div>
        <%end%>
    </section>
  </main>
</body>
</html>

app/views/events/show.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Événement</title>
</head>
<body>
  <main>
    <%= render 'layouts/flash' %>
    <section class="hero_event">
        <div class="title_width_event">
          <h1 class="white hero_title"><%= @event.title%></h1>
        </div> 
      </section>
    <section class="section_center section_event"> 
      <div class="inline_event_infos">
        <div>
          <h2 class="event_title phrase_accroche">Phrase d'accroche sur une ou plusieurs lignes suivant le besoin</h2>
          <p class="citation"> Crée par <%= @event.user.first_name%> <%= @event.user.last_name%></p>
          <p class=margin_bottom_event><%= @event.description%></p>
          <div class=inline>
            <%=button_to "Réserver une place", checkout_create_path(total:@event.price, event_id: @event.id), class: "btn btn-primary btn_primary", data: {turbo: false}%>
            <%if current_user?(@event)%>
              <a href="/events/<%=@event.id%>/attendances" class="btn btn-primary btn_primary">Voir les participants</a>
            <%end%>
          </div>
        </div>
            <div class="description_event">
                <h2 class="event_title phrase_accroche white">Infos pratiques</h2>
              <div>
                <div class=infos_event>
                  <i class="bi bi-geo-alt-fill"></i> <%= @event.location%>
                </div>
                <div class=infos_event>
                  <i class="bi bi-calendar-event"></i> <%= @event.start_date.strftime('%d'"/"'%m'" à ""%H""h")%>
                </div>
                <div class=infos_event>
                  <i class="bi bi-clock-fill"></i> <%= @event.duration%> min
                </div>
              </div>
            </div>  
      </div>
    </section>
  </main>
</body>
</html>