config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  devise_for :users

  resources :events do
    resources :attendances, only: [:index]
  end
  resources :users, only: [:show, :update, :edit]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create :welcome_send

    validates :stripe_customer_id, presence: true
    belongs_to :user
    belongs_to :event

    def welcome_send()
        UserMailer.welcome_attendance(self).deliver_now
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

    def index()
        id = params[:event_id]
        @event = Event.find(id)
    end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/index.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Participants de l'événement</title>
</head>
<body>
  <main>
    <%= render 'layouts/flash' %>
    <section class="hero_section">
      <div >
        <h1 class=white> Participants de l'événement </h1>
        <div class="btn btn_primary"><%= link_to "Modifier l'événement", edit_event_path(@event.id)%></div>
      </div> 
    </section>
    <section>
      <div class=price>
        <%= @event.users.count%>
      </div>
      <div class="participants">
        <div class=card_profil>
          <div class="inline_profil">
              <%if @event.users.count != 0%>
                <%@event.users.each do |user|%>
                <div class="profil_image"></div>
                  <p class=color_font_profil><%= user.first_name%> <%= user.last_name%></p>
                <%end%>
              <%elsif @event.users.count == 0%>
                <p>Il n'y a pas de participant pour le moment.</p>
              <%end%>
            </div>
          </div>
      </div>
      <div class="btn btn_primary"><%= link_to "Retour", event_path(@event.id)%></div>   
    </section>
  </main>
</body>
</html>